name: Unittest

on:
  push:
    paths:
      - '.github/workflows/unittest.yaml'
      - 'lang/**'
      - 'library/**'
      - 'WORKSPACE'
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: Homebrew/actions/setup-homebrew@master

      - name: mount conan cache
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-${{ runner.os }}-${{ hashFiles('build/conan/conanfile.txt') }}

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Install tools
        run: |
          sudo apt-get install -y cmake ninja-build lld
          brew install conan go-task/tap/go-task

      - name: install conan package
        run: task
        working-directory: build/conan

      - name: setup buildbuddy
        run: |
          echo 'build --bes_results_url=https://app.buildbuddy.io/invocation/' >> .bazelrc
          echo 'build --bes_backend=grpcs://remote.buildbuddy.io' >> .bazelrc
          echo 'build --remote_cache=grpcs://remote.buildbuddy.io' >> .bazelrc
          echo 'build --remote_timeout=3600' >> .bazelrc
          echo 'build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API }}' >> .bazelrc

      - run: bazel build --remote_download_minimal //...
      - run: bazel test //...

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
